name: fans
description: A new Flutter project.
publish_to: none
version: 1.0.0+4
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.7.0
  dio: ^3.0.7
  redux_logging: ^0.4.0
  logging: ^0.11.4
  video_player: ^1.0.1
  flutter_svg: ^0.19.2+1
  r_dart_library: ^0.2.1
  shared_preferences: ^0.5.12+4
  pull_to_refresh: ^1.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.3
flutter:
  uses-material-design: true
  assets:
  - assets/images/auth/eyes_visibility.png
  - assets/images/auth/eyes_visibility_off.png
  - assets/images/auth_background.png
  - assets/images/feed/ad_avatar_placeholder.png
  - assets/images/feed/add_cart.png
  - assets/images/feed/avatar_placeholder.png
  - assets/images/feed/cart.png
  - assets/images/feed/favorite.png
  - assets/images/feed/new_msg_tip_bg.png
  - assets/images/feed/pause.png
  - assets/images/feed/play.png
  - assets/images/feed/vip.png
  - assets/images/feed/voice_mute.png
  - assets/images/feed/voice_unmute.png
  - assets/images/interest_selected.png
  - assets/images/interest_unselected.png
  - assets/images/logo.png
  - assets/images/tabbar/tabbar_home_highlight.png
  - assets/images/tabbar/tabbar_home_normal.png
  - assets/images/tabbar/tabbar_inbox_hightlight.png
  - assets/images/tabbar/tabbar_inbox_normal.png
  - assets/images/tabbar/tabbar_profile_hightlight.png
  - assets/images/tabbar/tabbar_profile_normal.png
  - assets/images/tabbar/tabbar_search_highlight.png
  - assets/images/tabbar/tabbar_search_normal.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 100
  assets:
  - assets/images
