name: fans
description: A new Flutter project.
publish_to: none
version: 1.0.0+4
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.7.0
  redux: ^4.0.0+3
  dio: ^3.0.7
  redux_logging: ^0.4.0
  logging: ^0.11.4
  video_player: ^2.0.0-nullsafety.7
  flutter_svg: ^0.20.0-nullsafety.3
  r_dart_library: ^0.2.1
  shared_preferences: ^0.5.12+4
  flutter_easyrefresh: ^2.1.8
  flutter_easyloading: ^2.2.2
  intl: ^0.16.1
  modal_bottom_sheet: ^1.0.0+1
  throttling: ^0.9.0
  flutter_staggered_grid_view:
    git:
      url: 'https://github.com/letsar/flutter_staggered_grid_view.git'
  url_launcher: ^5.7.10
  photo_view: ^0.10.3
  flutter_widget_from_html_core: ^0.5.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.3
flutter:
  uses-material-design: true
  assets:
  - assets/images/auth/auth_background.png
  - assets/images/auth/eyes_visibility.png
  - assets/images/auth/eyes_visibility_off.png
  - assets/images/auth/interest_selected.png
  - assets/images/auth/interest_unselected.png
  - assets/images/feed/ad_avatar_placeholder.png
  - assets/images/feed/add_cart.png
  - assets/images/feed/avatar_placeholder.png
  - assets/images/feed/cart.png
  - assets/images/feed/favorite.png
  - assets/images/feed/idol_avatar_placeholder.png
  - assets/images/feed/idol_default_bg.png
  - assets/images/feed/more_vert.png
  - assets/images/feed/new_msg_tip_bg.png
  - assets/images/feed/pause.png
  - assets/images/feed/play.png
  - assets/images/feed/product_mask_bg.png
  - assets/images/feed/shopping_cart.png
  - assets/images/feed/verified.png
  - assets/images/feed/voice_mute.png
  - assets/images/feed/voice_unmute.png
  - assets/images/kol/kol_album_bg.png
  - assets/images/kol/kol_cart.png
  - assets/images/kol/kol_detail_bg.png
  - assets/images/kol/kol_tab_album.png
  - assets/images/kol/kol_tab_album_unselected.png
  - assets/images/kol/kol_tab_photos.png
  - assets/images/kol/kol_tab_photos_unselected.png
  - assets/images/logo.png
  - assets/images/product/cart_empty.png
  - assets/images/product/common_button_bg.png
  - assets/images/product/icon_payment.png
  - assets/images/product/icon_shipping.png
  - assets/images/product/payment_success.png
  - assets/images/product/paypal.png
  - assets/images/product/product_search.png
  - assets/images/tabbar/tabbar_home_highlight.png
  - assets/images/tabbar/tabbar_home_normal.png
  - assets/images/tabbar/tabbar_inbox_hightlight.png
  - assets/images/tabbar/tabbar_inbox_normal.png
  - assets/images/tabbar/tabbar_profile_hightlight.png
  - assets/images/tabbar/tabbar_profile_normal.png
  - assets/images/tabbar/tabbar_search_highlight.png
  - assets/images/tabbar/tabbar_search_normal.png
flr:
  core_version: 3.1.0
  dartfmt_line_length: 100
  assets:
  - assets/images
