# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger codemagic
        run: curl -XPOST https://api.codemagic.io/hooks/5fedcedde66e001e7e9d9b41
